# Generated by Django 5.0.2 on 2024-03-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeadLetterLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('error', models.CharField(max_length=25000, null=True)),
                ('event', models.CharField(max_length=25000)),
                ('is_retryable', models.BooleanField()),
                ('retries_made', models.IntegerField()),
            ],
        ),
    ]
