# Generated by Django 5.0.3 on 2024-03-10 09:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCycle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(db_index=True, null=True)),
                ('end_date', models.DateTimeField(db_index=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('fee', models.PositiveIntegerField(default=0)),
                ('reward', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'open'), ('complete', 'complete')], default='open', max_length=20)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500, null=True)),
                ('credit', models.PositiveIntegerField(default=0)),
                ('debit', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('payout', 'payout'), ('company', 'company')], max_length=128)),
                ('billing_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.billingcycle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
