# Generated by Django 5.0.2 on 2024-03-17 12:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='public_id',
            field=models.UUIDField(default=uuid.UUID('5d879873-8fe6-4345-8502-9a0e6e8302d1'), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='public_id',
            field=models.UUIDField(default=None, null=True),
        ),
    ]
