# Generated by Django 5.0.2 on 2024-03-03 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fee', models.PositiveIntegerField(default=0)),
                ('reward', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'open'), ('complete', 'complete')], default='open', max_length=20)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
